# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  vcpkgGitRef: 0ee4f000bd3405ab79be4f005f778ba3c314b2e5

steps:
- script: echo Create MeshTools
  displayName: 'MeshTools started'
- script: |
    sudo apt -y update
    sudo apt install build-essential -y
- task: Cahce@2
  displayName: "Cache vcpgk's artifacts"
  inputs:
    key: $(Build.SourcesDirectory)/vcpkg_x64-linux.txt | "$(vcpkgGitRef)" | "$(Agent.OS)"
    path: '$(Build.BinariesDirectory)/vcpkg'  

- task: run-vcpkg@0
  displayName: 'Run vcpkg'
  inputs:
    vcpkgArguments: $(Build.SourcesDirectory)/vcpkg_x64-linux.txt
    vcpkgGitCommitId: $(vcpkgGitRef)

- script: |
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg install boost-system booost-filesystem boost-iostreams boost-program-options
- task: CMake@1
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  displayName: 'CMake --build . --config Release'
  inputs:
    cmakeArgs: '--build . --config Release'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
